apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotlin-hello-world-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kotlin-hello-world
  template:
    metadata:
      name: kotlin-hello-world
      labels:
        app: kotlin-hello-world
    spec:
      containers:
        - name: kotlin-hello-world-container
          image: kotlin-hello-world
          imagePullPolicy: Never