apiVersion: v1
kind: Service
metadata:
  name: kotlin-hello-world-service
spec:
  type: NodePort
  selector:
    app: kotlin-hello-world
  ports:
    - targetPort: 8080
      nodePort: 30008
      port: 80